### ISSUE TITLE
help me to add code for deleting task

### ISSUE THREAD

**Issue by waseemmaya** [waseemmaya/ToDo-JS#1]
Hey Concern,

I need your help to delete todo task.

website link:
https://js-to-do.firebaseapp.com/

**Comment by IrfanAli17899** [comment]
Dear @waseemmaya As You Add Todo Object To The Data-Base On A Particular Ref All What You Have To Do Is That You Have To Set Empty Object And On That Ref In Data-Base And It Will Automaticaly Delete It
